/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArshjulRouteImport } from './routes/_authenticated/arshjul'
import { Route as AuthenticatedAvvikelserRouteImport } from './routes/_authenticated/avvikelser'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMalRouteImport } from './routes/_authenticated/mal'
import { Route as AuthenticatedManadMonthRouteImport } from './routes/_authenticated/manad.$month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArshjulRoute = AuthenticatedArshjulRouteImport.update({
  id: '/arshjul',
  path: '/arshjul',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvvikelserRoute = AuthenticatedAvvikelserRouteImport.update({
  id: '/avvikelser',
  path: '/avvikelser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMalRoute = AuthenticatedMalRouteImport.update({
  id: '/mal',
  path: '/mal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManadMonthRoute = AuthenticatedManadMonthRouteImport.update({
  id: '/manad/$month',
  path: '/manad/$month',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arshjul': typeof AuthenticatedArshjulRoute
  '/avvikelser': typeof AuthenticatedAvvikelserRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mal': typeof AuthenticatedMalRoute
  '/manad/$month': typeof AuthenticatedManadMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arshjul': typeof AuthenticatedArshjulRoute
  '/avvikelser': typeof AuthenticatedAvvikelserRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mal': typeof AuthenticatedMalRoute
  '/manad/$month': typeof AuthenticatedManadMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arshjul': typeof AuthenticatedArshjulRoute
  '/_authenticated/avvikelser': typeof AuthenticatedAvvikelserRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mal': typeof AuthenticatedMalRoute
  '/_authenticated/manad/$month': typeof AuthenticatedManadMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arshjul'
    | '/avvikelser'
    | '/dashboard'
    | '/mal'
    | '/manad/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arshjul'
    | '/avvikelser'
    | '/dashboard'
    | '/mal'
    | '/manad/$month'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arshjul'
    | '/_authenticated/avvikelser'
    | '/_authenticated/dashboard'
    | '/_authenticated/mal'
    | '/_authenticated/manad/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arshjul': {
      id: '/_authenticated/arshjul'
      path: '/arshjul'
      fullPath: '/arshjul'
      preLoaderRoute: typeof AuthenticatedArshjulRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avvikelser': {
      id: '/_authenticated/avvikelser'
      path: '/avvikelser'
      fullPath: '/avvikelser'
      preLoaderRoute: typeof AuthenticatedAvvikelserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mal': {
      id: '/_authenticated/mal'
      path: '/mal'
      fullPath: '/mal'
      preLoaderRoute: typeof AuthenticatedMalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manad/$month': {
      id: '/_authenticated/manad/$month'
      path: '/manad/$month'
      fullPath: '/manad/$month'
      preLoaderRoute: typeof AuthenticatedManadMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArshjulRoute: typeof AuthenticatedArshjulRoute
  AuthenticatedAvvikelserRoute: typeof AuthenticatedAvvikelserRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMalRoute: typeof AuthenticatedMalRoute
  AuthenticatedManadMonthRoute: typeof AuthenticatedManadMonthRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArshjulRoute: AuthenticatedArshjulRoute,
  AuthenticatedAvvikelserRoute: AuthenticatedAvvikelserRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMalRoute: AuthenticatedMalRoute,
  AuthenticatedManadMonthRoute: AuthenticatedManadMonthRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
